export const ADD_ITEM_TO_CART_REQUEST = "ADD_ITEM_TO_CART_REQUEST";
export const ADD_ITEM_TO_CART_SUCCESS = "ADD_ITEM_TO_CART_SUCCESS";
export const ADD_ITEM_TO_CART_FAIL = "ADD_ITEM_TO_CART_FAIL";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";

export const CREATE_NEW_ORDER = "CREATE_NEW_ORDER";
export const DELETE_OLD_ORDER = "DELETE_OLD_ORDER";
export const UPDATE_PAY_ORDER = "UPDATE_PAY_ORDER";
