export const RES_DETAILS_REQUEST = 'RES_DETAILS_REQUEST'
export const RES_DETAILS_SUCCESS = 'RES_DETAILS_SUCCESS'
export const RES_DETAILS_FAIL = 'RES_DETAILS_FAIL'

export const SINGLE_RES_DETAILS_REQUEST = 'SINGLE_RES_DETAILS_REQUEST'
export const SINGLE_RES_DETAILS_SUCCESS = 'SINGLE_RES_DETAILS_SUCCESS'
export const SINGLE_RES_DETAILS_FAIL = 'SINGLE_RES_DETAILS_FAIL'

export const RECIPES_DETAILS_REQUEST = 'RECIPES_DETAILS_REQUEST'
export const RECIPES_DETAILS_SUCCESS = 'RECIPES_DETAILS_SUCCESS'
export const RECIPES_DETAILS_FAIL = 'RECIPES_DETAILS_FAIL'
